apiVersion: v1
kind: Service
metadata:
  name: stateful-experiment-api
spec:
  ports:
  - name: grpc
    port: 2350
  selector:
    app: stateful-experiment

---
apiVersion: v1
kind: Service
metadata:
  name: stateful-experiment
spec:
  ports:
  - name: grpc
    port: 2350
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: stateful-experiment
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-experiment
spec:
  selector:
    matchLabels:
      app: stateful-experiment # must match .spec.template.metadata.labels
  serviceName: stateful-experiment
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: stateful-experiment # must match .spec.selector.matchLabels
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - stateful-experiment
      containers:
      - name: stateful-experiment
        image: stateful-experiment:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DUMMY_DB_ADDRESS
          value: "dummy-db.voltha.svc.cluster.local:2345"
        - name: PEER_DNS_FORMAT
          value: "stateful-experiment-%d.stateful-experiment.voltha.svc.cluster.local:2350"
        - name: LISTEN_ADDRESS
          value: ":2350"
        ports:
        - name: grpc
          containerPort: 2350
        - name: readiness
          containerPort: 2351
#        readinessProbe:
#          tcpSocket:
#            port: 2351
#          initialDelaySeconds: 0
#          timeoutSeconds: 1
#          periodSeconds: 5
#          successThreshold: 1
#          failureThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: dummy-db
spec:
  ports:
  - name: grpc
    port: 2345
  selector:
    app: dummy-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-db
  template:
    metadata:
      labels:
        app: dummy-db
    spec:
      containers:
      - name: dummy-db
        image: dummy-db:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: LISTEN_ADDRESS
            value: ":2345"
        ports:
        - containerPort: 2345